---
title: Creating Dunning Rules
nav_label: Creating Dunning Rules
sidebar_position: 20
---

Subscriptions enables you to create a dunning rule that allows you to configure payment retry schedules. Subscriptions retries failed payments automatically. You can customize the timing and frequency of the payment retries.

Dunning is enabled by default. If no dunning rule is configured, then payment is retried once a day for 10 days, in total 11 payments. You can decide what action to take after the Subscriptions has stopped retrying the payments.

If you configure a dunning rule, the dunning rule becomes the default for your store. All invoices in your store will then perform dunning according to the specified rules.

1. Go to **Subscriptions** > **Dunning and Prorations**.
2. Select **Dunning Rulesets**.
3. Configure the following:

    | Option             | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
    |--------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
    | Retry payment unit | The unit of time used to measure the intervals between payment attempts or retries, days or weeks.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
    | Retry payment interval | The number of retry payment units (for example, days or weeks) to wait between each payment retry attempt                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
    | Retry payment limit | The number of times subscriptions attempts payments retries before an action is taken.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
    | Action | The action to take if payment is not successful. You have the following options: <ul><li>Keep active - the subscription remains active and Subscriptions does not attempt to retry the payment. However, the subscription is still available for a subscriber to use.</li><li>Paused -  the subscription. Subscriptions does not attempt to retry the payment. A subscriber can choose to pay the outstanding invoice. However, a subscriber cannot renew their subscription; a merchandizer must renew the subscription on behalf of the subscriber.</li><li>Closed -  the subscription ends and it's status becomes inactive. However, a merchandizer can choose to resume the subscription if a subscriber pays the outstanding payment.</li></ul> |
4. Select **Save**.
5. You can update the dunning rule at anytime.

