---
title: Viewing Product Details
nav_label: Viewing Product Details
sidebar_position: 100
---

You can view your products in **Product Experience Manager > Products**. 

The following details are displayed:

| Name | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| --- |----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **Name** | The name of the product.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| **SKU** | The unique stock keeping unit of the product.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| **Type** | Whether the product type is: <ul><li>**Product** - a parent product. See [Assigning Variations and Building Child Products](/docs/commerce-manager/product-experience-manager/variations/assign-variations-build-child-products).</li><li>**Bundle** - a product bundle. See [Bundles in Commerce Manager](/docs/commerce-manager/product-experience-manager/bundles/bundle-configuration).</li><li>**Child** - a child product. See See [Assigning Variations and Building Child Products](/docs/commerce-manager/product-experience-manager/variations/assign-variations-build-child-products).</li></ul> |
| **Status** | The product status. <ul><li>**Draft**</li><li>**Live** - Only products with a **live** status are published in catalogs.</li></ul>                                                                                                                                                                                                                                                                                                                                                                                                                       |
| **Created** | The date and time a product is created.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| **Updated** | The date and time a product was last updated.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |

