---
title: Viewing Invoices
nav_label: Viewing Invoices
sidebar_position: 15
---

You can view your invoices in Commerce Manager.

1. To do this, go to **Subscriptions** > **Invoicing**. A list of your invoices is displayed.

    | Option               | Description                                                                                                                                                                              |
    |----------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
    | **Invoice ID**       | A unique identifier for an invoice.                                                                                                                                                      |
    | **Created**          | The date and time an invoice is created.                                                                                                                                                 |
    | **Subscriber ID**    | The unique identifier of a subscriber who generated an invoice.                                                                                                                          |
    | **Tax Required**     | Whether tax is required for an invoice.                                                                                                                                                  |
    | **Tax Status**       | One of the following: <ul><li>**Tax Applied** - Tax is applied.</li><li>**Pending Tax** - the tax amount is not yet finalized.</li><li>**Not Required** - Tax is not required.</li></ul> |
    | **Payment Status**   | One of the following: <ul><li>**Paid** - The invoice is paid.</li><li>**Unpaid** - payment is outstanding.</li></ul>                                                                     | 
2. Select an invoice to view an invoice's details.

    | Option                      | Description                                                                                                                                                                                                                                                                                                                                                                                                                                     |
    |-----------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
    | **Payment Status**          | One of the following: <ul><li>**Paid** - The invoice is paid.</li><li>**Unpaid** - payment is outstanding.</li></ul>                                                                                                                                                                                                                                                                                                                            |
    | **Invoice ID**              | A unique identifier for an invoice.                                                                                                                                                                                                                                                                                                                                                                                                             |
    | **Subscription ID**         | A unique identifier for the subscription generating the invoice.                                                                                                                                                                                                                                                                                                                                                                                |
    | **Created**                 | The date and time an invoice is created.                                                                                                                                                                                                                                                                                                                                                                                                        |
    | **Billed to Subscriber**    | The subscriber name, Email address and, ID.                                                                                                                                                                                                                                                                                                                                                                                                     |
    | **Billing Period**          | The billing period start date and end date. See [Creating Plans](/docs/commerce-manager/subscriptions/subscription-plans/creating-plans).                                                                                                                                                                                                                                                              |
    | **Billing Period length**:  | The billing period length. See [Creating Plans](/docs/commerce-manager/subscriptions/subscription-plans/creating-plans).                                                                                                                                                                                                                                                                                                                                                                                                                     |
    | **Tax Required**            | Whether tax is required for an invoice.                                                                                                                                                                                                                                                                                                                                                                                                         |
    | **Tax Status**              | One of the following: <ul><li>**Tax Applied** - Tax is applied.</li><li>**Pending Tax** - the tax amount is not yet finalized.</li><li>**Not Required** - Tax is not required.</li></ul>                                                                                                                                                                                                                                                        |
    | **Payment Attempts**        | In Subscriptions, by default, the number of payment retries is 10. You can set this to a limit between 0 - 20, depending on your requirements. Each payment retry is made as a payment run. Once the number of payment retries reaches the limit, the payment retries stop, resulting in the status of the invoice being unpaid. See [Creating Dunning Rules](/docs/commerce-manager/subscriptions/dunning-proration/dunning/creating-dunning). |
    | **Payment ID**                  | A unique identifier for a payment.                                                                                                                                                                                                                                                                                                                                                                                                              |
    | **Payment Status**          | One of the following: <ul><li>**Paid** - The invoice is paid.</li><li>**Unpaid** - payment is outstanding.</li></ul>                                                                                                                                                                                                                                                                                                                            | 
    | **Report**                      | You can use the report to track your payment operations in Subscriptions. See [Billing, Tax & Payment reports](/docs/api/subscriptions/jobs#billing-tax--payment-reports).                                                                                                                                                                                                                                                                      |
    | **Product Description**         | The description of the subscription product. See [Creating Repeat Products](/docs/commerce-manager/subscriptions/products/creating-products).                                                                                                                                                                                                                                                                                                   |
    | **Pricing**                     | The product price. See [Product Pricing](/docs/commerce-manager/subscriptions/products/managing-products-cm#product-pricing).                                                                                                                                                                                                                                                                                                                   |
    | **Product Price Includes Tax?** | Whether the product price includes tax.                                                                                                                                                                                                                                                                                                                                                                                                         | 


